import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Link from "next/link"
import { CssBaseline, Stack } from "@mui/material"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function TableLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      {/* <CssBaseline />
      <Stack
        height='100vh'
        overflow='hidden'
        component='body'
        className={inter.className}
      >
        <header>
          <Link href='/'>
            <h1>Vat Calculator</h1>
          </Link>
        </header> */}
        <Stack component='main' flex='1' overflow={"hidden"} position="relative" >
          {children}
        </Stack>
      {/* </Stack> */}
      </>
  )
}
