type Month = 'JAN' | 'FEB' | 'MAR' | 'APR' | 'MAY' | 'JUN' | 'JUL' | 'AUG' | 'SEP' | 'OCT' | 'NOV' | 'DEC'

export type AmazonData = {
  UNIQUE_ACCOUNT_IDENTIFIER: string,
  ACTIVITY_PERIOD: '2024-JAN',
  SALES_CHANNEL: 'AFN' | 'MFN',
  MARKETPLACE: 'amazon.co.uk' | 'amazon.pl' | 'amazon.com.be' | 'amazon.de' | 'amazon.fr' | 'amazon.it' | 'amazon.es' | 'amazon.nl' | 'amazon.se' | 'amazon.pl' | 'amazon.com.tr' | 'amazon.ae' | 'amazon.sa' | 'amazon.com' | 'amazon.ca' | 'amazon.com.mx' | 'amazon.com.br' | 'amazon.com.au' | 'amazon.co.jp' | 'amazon.in' | 'amazon.sg' | 'amazon.cn',
  PROGRAM_TYPE: 'REGULAR',
  TRANSACTION_TYPE: 'SALE',
  TRANSACTION_EVENT_ID: '204-0198257-9890714',
  ACTIVITY_TRANSACTION_ID: 'UXjhCz54v',
  TAX_CALCULATION_DATE: '31-01-2024',
  TRANSACTION_DEPART_DATE: '31-01-2024',
  TRANSACTION_ARRIVAL_DATE: '',
  TRANSACTION_COMPLETE_DATE: string,
  SELLER_SKU: '1T.easy.bo',
  ASIN: 'B00L9AP212',
  ITEM_DESCRIPTION: 'CleanAid OneTouch Easy Floor Mop - Floor Sponge Mop with Telescopic Handle, Inbuilt Wringer and Highly-Absorbent PVA Sponge - Floor Cleaning Mop for Kitchen, Bathroom and Around the Home',
  ITEM_MANUFACTURE_COUNTRY: '',
  QTY: '1',
  ITEM_WEIGHT: '0.73',
  TOTAL_ACTIVITY_WEIGHT: '0.73',
  COST_PRICE_OF_ITEMS: '',
  PRICE_OF_ITEMS_AMT_VAT_EXCL: string,
  PROMO_PRICE_OF_ITEMS_AMT_VAT_EXCL: '-0.92',
  TOTAL_PRICE_OF_ITEMS_AMT_VAT_EXCL: '17.4',
  SHIP_CHARGE_AMT_VAT_EXCL: '0.0',
  PROMO_SHIP_CHARGE_AMT_VAT_EXCL: '',
  TOTAL_SHIP_CHARGE_AMT_VAT_EXCL: '0.0',
  GIFT_WRAP_AMT_VAT_EXCL: '',
  PROMO_GIFT_WRAP_AMT_VAT_EXCL: '',
  TOTAL_GIFT_WRAP_AMT_VAT_EXCL: '',
  TOTAL_ACTIVITY_VALUE_AMT_VAT_EXCL: '17.4',
  PRICE_OF_ITEMS_VAT_RATE_PERCENT: string,
  PRICE_OF_ITEMS_VAT_AMT: '0.0',
  PROMO_PRICE_OF_ITEMS_VAT_AMT: '0.0',
  TOTAL_PRICE_OF_ITEMS_VAT_AMT: '0.0',
  SHIP_CHARGE_VAT_RATE_PERCENT: '0.0',
  SHIP_CHARGE_VAT_AMT: '0.0',
  PROMO_SHIP_CHARGE_VAT_AMT: '0.0',
  TOTAL_SHIP_CHARGE_VAT_AMT: '0.0',
  GIFT_WRAP_VAT_RATE_PERCENT: '',
  GIFT_WRAP_VAT_AMT: '0.0',
  PROMO_GIFT_WRAP_VAT_AMT: '0.0',
  TOTAL_GIFT_WRAP_VAT_AMT: '0.0',
  TOTAL_ACTIVITY_VALUE_VAT_AMT: string,
  PRICE_OF_ITEMS_AMT_VAT_INCL: '18.32',
  PROMO_PRICE_OF_ITEMS_AMT_VAT_INCL: '-0.92',
  TOTAL_PRICE_OF_ITEMS_AMT_VAT_INCL: '17.4',
  SHIP_CHARGE_AMT_VAT_INCL: '0.0',
  PROMO_SHIP_CHARGE_AMT_VAT_INCL: '0.0',
  TOTAL_SHIP_CHARGE_AMT_VAT_INCL: '0.0',
  GIFT_WRAP_AMT_VAT_INCL: '0.0',
  PROMO_GIFT_WRAP_AMT_VAT_INCL: '0.0',
  TOTAL_GIFT_WRAP_AMT_VAT_INCL: '0.0',
  TOTAL_ACTIVITY_VALUE_AMT_VAT_INCL: string,
  TRANSACTION_CURRENCY_CODE: 'GBP',
  COMMODITY_CODE: '',
  STATISTICAL_CODE_DEPART: '',
  STATISTICAL_CODE_ARRIVAL: '',
  COMMODITY_CODE_SUPPLEMENTARY_UNIT: '',
  ITEM_QTY_SUPPLEMENTARY_UNIT: '',
  TOTAL_ACTIVITY_SUPPLEMENTARY_UNIT: '',
  PRODUCT_TAX_CODE: 'A_GEN_STANDARD',
  DEPATURE_CITY: 'LIVERPOOL',
  DEPARTURE_COUNTRY: 'GB',
  DEPARTURE_POST_CODE: 'L33 7AP',
  ARRIVAL_CITY: 'ROCHESTER',
  ARRIVAL_COUNTRY: 'GB',
  ARRIVAL_POST_CODE: 'ME1 1ER',
  SALE_DEPART_COUNTRY: 'GB',
  SALE_ARRIVAL_COUNTRY: 'GB',
  TRANSPORTATION_MODE: 'CONSIGNMENT_BY_POST',
  DELIVERY_CONDITIONS: 'DAP',
  SELLER_DEPART_VAT_NUMBER_COUNTRY: 'GB',
  SELLER_DEPART_COUNTRY_VAT_NUMBER: 'GB264566381',
  SELLER_ARRIVAL_VAT_NUMBER_COUNTRY: 'GB',
  SELLER_ARRIVAL_COUNTRY_VAT_NUMBER: 'GB264566381',
  TRANSACTION_SELLER_VAT_NUMBER_COUNTRY: 'GB',
  TRANSACTION_SELLER_VAT_NUMBER: 'GB264566381',
  BUYER_VAT_NUMBER_COUNTRY: '',
  BUYER_VAT_NUMBER?: string,
  VAT_CALCULATION_IMPUTATION_COUNTRY: 'GB',
  TAXABLE_JURISDICTION: 'UNITED KINGDOM',
  TAXABLE_JURISDICTION_LEVEL: 'Country',
  VAT_INV_NUMBER: string,
  VAT_INV_CONVERTED_AMT: '',
  VAT_INV_CURRENCY_CODE: '',
  VAT_INV_EXCHANGE_RATE: '',
  VAT_INV_EXCHANGE_RATE_DATE: '',
  EXPORT_OUTSIDE_EU: 'NO' | 'YES',
  INVOICE_URL: 'https://www.Amazon.co.uk/gp/invoice/download.html?v=urn%3aalx%3adoc%3a9d8cab0f-1f96-4462-8642-ace99a371392%3a47fba0a5-7a44-429c-ba8d-eb3ca74a534c&t=EU_Retail_Forward',
  BUYER_NAME: '',
  ARRIVAL_ADDRESS: '',
  SUPPLIER_NAME: '',
  SUPPLIER_VAT_NUMBER: '',
  TAX_REPORTING_SCHEME: string,
  TAX_COLLECTION_RESPONSIBILITY: 'MARKETPLACE'
}

export type Invoice = {
  salesChannel: 'AFN' | 'MFN',
  vatInvoiceNumber: string,
  transactionDate: Date,
  buyerVatNumber?: string,
  departCountry: string,
  arrivalCountry: string,
  vatCountry: string,
  transactionId: string,
  vatRate: number,
  vat: number,
  grossSale: number,
  transactionCurrency: string,
  arrivalPostCode: string,
  arrivalCity: string,
  taxReportingScheme: string,
  isExportOutsideEU: string,
  taxResponsibility: string,
  netSale: number,
  EXCHANGE_RATE: number,
  vatEuro: number,
  grossSaleEuro: number,
  netSaleEuro: number,
  marketPlace: string,
  salesType: 'B2B' | 'B2C'
}

export type UnknownData = unknown[]

