import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Link from "next/link"
import { CssBaseline } from "@mui/material"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <CssBaseline/>
      <body className={inter.className}>
        <header>
          <Link href='/'>
          <h1>Vat Calculator</h1>
          </Link>
        </header>
        <main>{children}</main>
      </body>
    </html>
  )
}
