import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Link from "next/link"
import { CssBaseline, Stack } from "@mui/material"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <CssBaseline/>
      <Stack component="body" className={inter.className} padding={'20px'} gap={2} minHeight={"100vh"}>
        <header>
          <Link href='/'>
          <h1>Vat Calculator</h1>
          </Link>
        </header>
        <Stack component={"main"} position={"relative"} flex={"1"} overflow={"hidden"}>{children}</Stack>
      </Stack>
    </html>
  )
}
